### ISSUE TITLE
Make viewer path a config option in config.json

### ISSUE THREAD

**Issue by mikemitchel** [CCALI/A2JDAT#1]
The DAT viewer path is derived from Author code that expects it and the `guides` folder to be in a certain relative space. 
https://github.com/CCALI/CAJA/blob/bitovi/src/util/paths.js#L21

Update the code so that it can be explicitly defined in config.json as we did for the location of wkhtmltopdf.

**Comment by tobiasnteireho** [comment]
fixed in v2
