### ISSUE TITLE
Proxy error in console after assembly failed

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/A2JDAT#114]
Author reported error with this interview
[Autorización para representación en mediación (1).zip](https://github.com/CCALI/a2jdat/files/8112030/Autorizacion.para.representacion.en.mediacion.1.zip), using these answer files (but can replicate with any answer file)
[answer - 2022-02-21T145730.860.zip](https://github.com/CCALI/a2jdat/files/8112029/answer.-.2022-02-21T145730.860.zip)

{"ok":false,"error":"context not created, page index is either wrong, or page is null"} appears when you test assemble from templates tab. Template fails to assemble completely, but silently, from within the template itself. 

Console error: 
![image](https://user-images.githubusercontent.com/7662028/155025403-133419ed-5896-4868-a4c8-6bd3b57648fc.png)

I downloaded the pdf from the All Files tab. It didn't look to have fillable fields, however I couldn't edit it because it required a password. Tried converting/editing it in Adobe Pro and PDFfill 

I checked the variables in the template and they all looked as expected.

**Comment by tobiasnteireho** [comment]
Issue is fixed after flattening pdf 
https://a2j.org/guide/go/870f69de-a9f8-41fe-9e91-ee6fcda2bc1d
[Autorización para representación en mediación.zip](https://github.com/CCALI/a2jdat/files/8112596/Autorizacion.para.representacion.en.mediacion.zip)
f

**Comment by tobiasnteireho** [comment]
I suspect the proxy error is a result of a 500 from express coming through apache or possibly an error issued by express due to the exception being thrown.

**Comment by tobiasnteireho** [comment]
related to #133
