### ISSUE TITLE
upgrade to node 14 or 16

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/A2JDAT#67]
node 12 goes EOL 2022-04-30

**Comment by tobiasnteireho** [comment]
DAT confirmed to work fine in node 16 for 7.0.9

**Comment by mitch-mitchel** [comment]
https://stackoverflow.com/a/50798589

tells how to enforce node versions above - could be useful for us on this, especially if folks start doing OS contributions

**Comment by tobiasnteireho** [comment]
fixed by #119
